### ISSUE TITLE
Linux下如何使用80端口

### ISSUE THREAD

**Issue by NewFuture** [YunYinORG/vagrant#2]
@LimitW

**Comment by LimitW** [comment]
1.update local port of vagrant-file
2.redirect 80 port to your local port
iptables -t nat -A PREROUTING -s 127.0.0.1 -p tcp --dport 80 -j REDIRECT --to-ports LOCAL_PORT
iptables -t nat -A OUTPUT -s 127.0.0.1 -p tcp --dport 80 -j REDIRECT --to-ports LOCAL_PORT

Source: http://stackoverflow.com/questions/28170004/how-to-do-local-port-forwarding-with-iptables
